-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:02:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema metro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metro` DEFAULT CHARACTER SET utf8 ;
USE `metro` ;

-- -----------------------------------------------------
-- Table `metro`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`point` (
  `idpoint` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `positionx` INT NOT NULL,
  `positiony` INT NOT NULL,
  PRIMARY KEY (`idpoint`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metro`.`path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`path` (
  `idpath` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  `left` INT NOT NULL,
  `right` INT NOT NULL,
  `point_leftID` INT NOT NULL,
  `point_rightID` INT NOT NULL,
  PRIMARY KEY (`idpath`, `point_leftID`, `point_rightID`),
  INDEX `fk_path_point_idx` (`point_leftID` ASC) ,
  INDEX `fk_path_point1_idx` (`point_rightID` ASC) ,
  CONSTRAINT `fk_path_point`
    FOREIGN KEY (`point_leftID`)
    REFERENCES `metro`.`point` (`idpoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_path_point1`
    FOREIGN KEY (`point_rightID`)
    REFERENCES `metro`.`point` (`idpoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
